import { KNOWN_CHANNELS } from "../../lib/channel-defs.js";
import type { ChannelsStatusSnapshot, ChannelAccountSnapshot } from "../../api/index.js";

export function StatusBadge({ status, t }: { status: boolean | null | undefined; t: (key: string) => string }) {
  const variant = status === true ? "badge-success" : status === false ? "badge-danger" : "badge-warning";
  const text = status === true ? t("channels.statusYes") : status === false ? t("channels.statusNo") : t("channels.statusUnknown");

  return (
    <span className={`badge ${variant}`}>
      {text}
    </span>
  );
}

/** Return all known channels (no locale-based filtering). */
export function getVisibleChannels(_lang: string, _selectedDropdownChannel: string) {
  return [...KNOWN_CHANNELS];
}

export interface AccountEntry {
  channelId: string;
  channelLabel: string;
  account: ChannelAccountSnapshot;
}

/** Build the unified accounts list from snapshot, filtering synthetic defaults. */
export function buildAccountsList(
  snapshot: ChannelsStatusSnapshot,
  t: (key: string) => string,
): AccountEntry[] {
  const allAccounts: AccountEntry[] = [];

  for (const [channelId, accounts] of Object.entries(snapshot.channelAccounts)) {
    const knownChannel = KNOWN_CHANNELS.find(c => c.id === channelId);
    const channelLabel = knownChannel ? t(knownChannel.labelKey) : snapshot.channelLabels[channelId] || channelId;

    for (const account of accounts) {
      // Skip synthetic "default" placeholder accounts (auto-generated by gateway when no config exists)
      const isSyntheticDefault =
        account.accountId === "default" &&
        account.configured === false &&
        !account.name &&
        (account as any).tokenSource === "none";

      if (isSyntheticDefault) continue;
      allAccounts.push({ channelId, channelLabel, account });
    }
  }

  return allAccounts;
}
